version: '3.1'

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - "mysql-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker

volumes:
  mysql-data: